"""Private decomposition kernels for multi-controlled gates.

Implements two decomposition strategies:

Barenco mode (clean ancilla):
    Uses Barenco et al. (1995) Lemma 7.5 (two-half dirty-ancilla scheme).
    Requires one clean ancilla qubit in |0>.  O(n) depth.

V-chain mode (no ancilla):
    Linear-Depth Decomposition (LDD) from da Silva & Park 2022
    (arXiv:2203.11882, Phys. Rev. A 106, 042602).  Specialised here to
    C^n(X).  Total gate count is exactly **2*n^2** primitive 1q+2q gates
    for n >= 2 controls, i.e. polynomial (O(n^2)), no ancilla.

    The construction emits four blocks of "fractional X" operations.
    Operating on local indices 0..n_q-1 with the target at local index
    n_q-1 = n_controls:

        Block 1: _emit_ldd_block(n_q,     first=True,  step=+1)
        Block 2: _emit_ldd_block(n_q,     first=True,  step=-1)
        Block 3: _emit_ldd_block(n_q-1,   first=False, step=+1)
        Block 4: _emit_ldd_block(n_q-1,   first=False, step=-1)

    Each block iterates over qubit pairs (pc, pt) generated by
    ``_c1c2_pairs(n, step)`` and emits, for each pair, either:
      - A controlled fractional X (P + CRx) on (pc -> target) when
        pt == n_q-1 and first=True;
      - A plain CRx(theta) on (pc -> pt) otherwise.

    Single ISA primitive used for the controlled "fractional X":
        X^(1/k)              = e^(i*pi/(2k)) * Rx(pi/k)
        C(X^(1/k))(c -> t)   = P(pi/(2k))(c) . CRx(pi/k)(c -> t)
        C(X^(-1/k))(c -> t)  = P(-pi/(2k))(c) . CRx(-pi/k)(c -> t)
        C(X^1)(c -> t)       = CX(c -> t)

All functions assume their arguments have already been validated by the
public API in multicontrol.py.  No **kwargs, no validation here.

Little-endian convention: qubit 0 is the LSB of the state-vector index,
matching _sim.py and _equiv_native.py.
"""
from typing import List, Optional
import math

from ..arch.instruction import Instruction
from ..arch.isa import ISA

# ---------------------------------------------------------------------------
# ISA-level building blocks
# ---------------------------------------------------------------------------

def _toffoli(isa: ISA, c0: int, c1: int, tg: int) -> List[Instruction]:
    """Standard Toffoli (CCX) decomposition into 1q + CX gates.

    Uses the classic T-gate decomposition (6 CX, 7 T/Tdg, 2 H).
    References: Nielsen & Chuang Fig 4.9; Selinger 2013.
    """
    result = [isa.h(tg=tg)]
    result.append(isa.cx(ct=c1, tg=tg))
    result.append(isa.tdg(tg=tg))
    result.append(isa.cx(ct=c0, tg=tg))
    result.append(isa.t(tg=tg))
    result.append(isa.cx(ct=c1, tg=tg))
    result.append(isa.tdg(tg=tg))
    result.append(isa.cx(ct=c0, tg=tg))
    result.append(isa.t(tg=tg))
    result.append(isa.t(tg=c1))
    result.append(isa.h(tg=tg))
    result.append(isa.cx(ct=c0, tg=c1))
    result.append(isa.t(tg=c0))
    result.append(isa.tdg(tg=c1))
    result.append(isa.cx(ct=c0, tg=c1))
    return result


# ---------------------------------------------------------------------------
# V-chain (no ancilla) decomposition — da Silva & Park 2022 LDD
# ---------------------------------------------------------------------------
#
# The LDD construction operates over a list of n_q qubit indices
# `qmap` (length n_q) representing local positions 0..n_q-1.  For our
# MCX use, qmap = controls + [target] so that the target is at local
# index n_q-1.  Pairs (pc, pt) generated by `_c1c2_pairs` index into
# qmap to produce physical qubits.

def _c1c2_pairs(n_qubits: int, step: int) -> List[tuple]:
    """Generate the (control_local, target_local) pair sequence for one
    LDD block.  `step` is +1 or -1 and controls the ordering.

    Mirrors qclib's `_c1c2` pair-generation routine.
    """
    if step == 1:
        start = 0
        reverse = True
    else:
        start = 1
        reverse = False
    pairs = [(c, t) for t in range(n_qubits) for c in range(start, t)]
    pairs.sort(key=lambda e: e[0] + e[1], reverse=reverse)
    return pairs


def _emit_ldd_block(
    isa: ISA,
    qmap: List[int],
    n_qubits: int,
    first: bool,
    step: int,
    result: List[Instruction],
) -> None:
    """Emit one of the four LDD blocks.

    Parameters
    ----------
    isa : ISA used to construct instructions.
    qmap : Sequence of physical qubit indices for local positions 0..n_q-1.
        For MCX, qmap = controls + [target].
    n_qubits : The "local" qubit count for THIS block.  May be smaller
        than len(qmap) (the later two blocks only act on the first
        n-1 qubits — i.e., the controls only).  The "endpoint target"
        in this block is local index n_qubits-1.
    first : True for the first two blocks (which include the endpoint
        controlled fractional-X on the global target); False for the
        latter two (which never touch the global target).
    step : +1 or -1, selects the pair-sort direction and the sign of
        the rotation angles.
    result : list to append instructions to (in place).

    Each emitted instruction uses only ISA-level primitives
    (`p`, `cx`, `crx`); no multi-control gates appear.
    """
    pairs = _c1c2_pairs(n_qubits, step)
    for pc, pt in pairs:
        exponent = pt - pc
        if pc == 0:
            exponent -= 1
        param = 1 << exponent          # 2 ** exponent
        signal = -1 if (pc == 0 and not first) else 1
        signal = step * signal
        theta = signal * math.pi / param

        ctrl_phys = qmap[pc]
        tgt_phys = qmap[pt]

        if pt == n_qubits - 1 and first:
            # Endpoint: controlled fractional X on the global target.
            #   X^(signal/param) = e^(i*signal*pi/(2*param)) * Rx(signal*pi/param)
            #   C-version: P(signal*pi/(2*param)) on ctrl + CRx(signal*pi/param)
            if param == 1:
                # X^(±1) = X (self-adjoint); a single CX suffices.
                result.append(isa.cx(ct=ctrl_phys, tg=tgt_phys))
            else:
                phase = signal * math.pi / (2 * param)
                rx_angle = signal * math.pi / param
                result.append(isa.p(tg=ctrl_phys, params=[phase]))
                result.append(isa.crx(ct=ctrl_phys, tg=tgt_phys,
                                     params=[rx_angle]))
        else:
            # Inner pair: plain CRx(theta) on (pc -> pt).
            result.append(isa.crx(ct=ctrl_phys, tg=tgt_phys, params=[theta]))


def _vchain_mcx_internal(isa: ISA, controls: List[int], target: int) -> List[Instruction]:
    """C^n(X) without ancilla via the Linear-Depth Decomposition (LDD)
    of da Silva & Park 2022 (arXiv:2203.11882).

    Produces exactly **2*n^2** primitive 1q+2q gates for n >= 2 controls,
    i.e. polynomial — no ancilla.

    Base cases:
        n=0: X(target)
        n=1: CX(controls[0] -> target)
        n>=2: four LDD blocks.

    The construction never emits an instruction with more than one
    control qubit (the load-bearing invariant for multicontrol_test).
    """
    n = len(controls)

    if n == 0:
        return [isa.x(tg=target)]
    if n == 1:
        return [isa.cx(ct=controls[0], tg=target)]

    # n >= 2: LDD.
    qmap = list(controls) + [target]   # local 0..n-1 = controls, local n = target
    n_q = n + 1                         # total number of qubits in the gate

    result: List[Instruction] = []
    # Block 1 + 2: act on the full n+1 qubits with first=True (touch target).
    _emit_ldd_block(isa, qmap, n_q,     first=True,  step=+1, result=result)
    _emit_ldd_block(isa, qmap, n_q,     first=True,  step=-1, result=result)
    # Block 3 + 4: act only on the first n_q-1 = n local positions
    # (i.e., the controls).  The target is not referenced here.
    _emit_ldd_block(isa, qmap, n_q - 1, first=False, step=+1, result=result)
    _emit_ldd_block(isa, qmap, n_q - 1, first=False, step=-1, result=result)
    return result


# ---------------------------------------------------------------------------
# Barenco clean-ancilla scheme (Lemma 7.5)
# ---------------------------------------------------------------------------

def _barenco_mcx(isa: ISA, controls: List[int], target: int,
                 ancilla: int) -> List[Instruction]:
    """Decompose MCX with n >= 3 controls using one clean ancilla.

    Uses Barenco et al. (1995) Lemma 7.5 (two-half scheme):
      1. MCX(lo → ancilla)  -- put partial AND result in ancilla
      2. MCX(hi + [ancilla] → target)  -- compute final result
      3. MCX(lo → ancilla)  -- restore ancilla to |0>
      4. MCX(hi + [ancilla] → target)  -- reapply to finalize

    For each recursive call, if it has <= 2 controls, use Toffoli directly.
    For longer sub-problems, recurse with further sub-ancillas taken from
    the "dirty" available qubits via the dirty-ancilla trick.
    """
    n = len(controls)

    if n == 1:
        return [isa.cx(ct=controls[0], tg=target)]
    if n == 2:
        return _toffoli(isa, controls[0], controls[1], target)

    # n >= 3: two-half split
    half = (n + 1) // 2
    lo = controls[:half]
    hi = controls[half:]

    def _sub_mcx(ctrls, tgt, dirty_pool):
        """MCX that may use dirty_pool[0] as a dirty ancilla if needed."""
        if len(ctrls) == 1:
            return [isa.cx(ct=ctrls[0], tg=tgt)]
        if len(ctrls) == 2:
            return _toffoli(isa, ctrls[0], ctrls[1], tgt)
        # Need an ancilla — grab from dirty pool
        if not dirty_pool:
            # Fall back to vchain (no clean ancilla available)
            return _vchain_mcx_internal(isa, ctrls, tgt)
        dirty_anc = dirty_pool[0]
        new_dirty = dirty_pool[1:] + [tgt]
        half2 = (len(ctrls) + 1) // 2
        lo2 = ctrls[:half2]
        hi2 = ctrls[half2:]
        instrs = []
        instrs.extend(_sub_mcx(lo2, dirty_anc, hi2 + new_dirty))
        instrs.extend(_sub_mcx(hi2 + [dirty_anc], tgt, lo2 + new_dirty))
        instrs.extend(_sub_mcx(lo2, dirty_anc, hi2 + new_dirty))
        instrs.extend(_sub_mcx(hi2 + [dirty_anc], tgt, lo2 + new_dirty))
        return instrs

    result = []
    result.extend(_sub_mcx(lo, ancilla, hi + [target]))
    result.extend(_sub_mcx(hi + [ancilla], target, lo))
    result.extend(_sub_mcx(lo, ancilla, hi + [target]))
    result.extend(_sub_mcx(hi + [ancilla], target, lo))
    return result


# ---------------------------------------------------------------------------
# Public decomposition functions
# ---------------------------------------------------------------------------

def decompose_mcx(
    isa: ISA,
    controls: List[int],
    target: int,
    mode: str,
    ancilla: Optional[int],
) -> List[Instruction]:
    """Decompose an n-controlled X (n >= 2) into 1q+2q gates.

    Preconditions (assumed, not checked):
      - len(controls) >= 2
      - target not in controls
      - mode in {"barenco", "vchain"}
      - if mode == "barenco": ancilla is not None and ancilla not in controls + [target]
    """
    if mode == "barenco":
        return _barenco_mcx(isa, controls, target, ancilla)
    else:
        return _vchain_mcx_internal(isa, controls, target)


def decompose_mcz(
    isa: ISA,
    controls: List[int],
    target: int,
    mode: str,
    ancilla: Optional[int],
) -> List[Instruction]:
    """MCZ via H-sandwich on target around an MCX.

    MCZ(c_0..c_{n-1}, t) = H_t . MCX(c_0..c_{n-1}, t) . H_t
    """
    result = []
    result.append(isa.h(tg=target))
    result.extend(decompose_mcx(isa, controls, target, mode, ancilla))
    result.append(isa.h(tg=target))
    return result


def decompose_mcry(
    isa: ISA,
    controls: List[int],
    target: int,
    theta: float,
    mode: str,
    ancilla: Optional[int],
) -> List[Instruction]:
    """Multi-controlled R_y(theta) via the conjugation pattern.

    MCRY(theta) = Ry(theta/2) . MCX . Ry(-theta/2) . MCX
    where MCX uses controls and the same mode/ancilla.
    """
    result = []
    result.append(isa.ry(tg=target, params=[theta / 2]))
    result.extend(decompose_mcx(isa, controls, target, mode, ancilla))
    result.append(isa.ry(tg=target, params=[-theta / 2]))
    result.extend(decompose_mcx(isa, controls, target, mode, ancilla))
    return result


def decompose_mcrz(
    isa: ISA,
    controls: List[int],
    target: int,
    theta: float,
    mode: str,
    ancilla: Optional[int],
) -> List[Instruction]:
    """Multi-controlled R_z(theta) via phase-kickback identity.

    MCRZ(theta) = Rz(theta/2) . MCX . Rz(-theta/2) . MCX
    where MCX uses controls and the same mode/ancilla.
    """
    result = []
    result.append(isa.rz(tg=target, params=[theta / 2]))
    result.extend(decompose_mcx(isa, controls, target, mode, ancilla))
    result.append(isa.rz(tg=target, params=[-theta / 2]))
    result.extend(decompose_mcx(isa, controls, target, mode, ancilla))
    return result
